#Nifty - 50 stocks 
nifty_50_stocks = {
    "RELIANCE": "Reliance Industries",
    "TCS": "Tata Consultancy Services",
    "INFY": "Infosys",
    "HDFCBANK": "HDFC Bank",
    "ICICIBANK": "ICICI Bank",
    "HINDUNILVR": "Hindustan Unilever",
    "SBIN": "State Bank of India",
    "ITC": "ITC Limited",
    "LT": "Larsen & Toubro",
    "KOTAKBANK": "Kotak Mahindra Bank",
    "BHARTIARTL": "Bharti Airtel",
    "ASIANPAINT": "Asian Paints",
    "BAJFINANCE": "Bajaj Finance",
    "HCLTECH": "HCL Technologies",
    "ADANIENT": "Adani Enterprises",
    "ADANIGREEN": "Adani Green Energy",
    "ADANIPORTS": "Adani Ports & SEZ",
    "DMART": "Avenue Supermarts",
    "MARUTI": "Maruti Suzuki",
    "M&M": "Mahindra & Mahindra",
    "SUNPHARMA": "Sun Pharmaceutical",
    "TITAN": "Titan Company",
    "ULTRACEMCO": "UltraTech Cement",
    "WIPRO": "Wipro",
    "AXISBANK": "Axis Bank",
    "BAJAJFINSV": "Bajaj Finserv",
    "NTPC": "NTPC Limited",
    "POWERGRID": "Power Grid Corp",
    "ONGC": "Oil & Natural Gas Corp",
    "JSWSTEEL": "JSW Steel",
    "COALINDIA": "Coal India",
    "DIVISLAB": "Divi's Laboratories",
    "TATASTEEL": "Tata Steel",
    "GRASIM": "Grasim Industries",
    "BPCL": "Bharat Petroleum",
    "INDUSINDBK": "IndusInd Bank",
    "TECHM": "Tech Mahindra",
    "DRREDDY": "Dr. Reddy’s Labs",
    "EICHERMOT": "Eicher Motors",
    "HEROMOTOCO": "Hero MotoCorp",
    "BAJAJ_AUTO": "Bajaj Auto",
    "BRITANNIA": "Britannia Industries",
    "CIPLA": "Cipla Ltd",
    "HDFCLIFE": "HDFC Life Insurance",
    "SBILIFE": "SBI Life Insurance",
    "ICICIPRULI": "ICICI Prudential Life",
    "HINDALCO": "Hindalco Industries",
    "NESTLEIND": "Nestlé India",
    "UPL": "UPL Limited",
    "TATAMOTORS": "Tata Motors",
    "NoStock": "NoStock"
}
